---
- hosts: localhost
  tasks:
    - name: Create pritunl container.
      docker_container:
        name: pritunl-base
        image: centos:7
        command: /bin/bash
        tty: yes
        state: started

- hosts: pritunl-base
  connection: docker
  roles:
    - role: shomatan.pritunl
  tasks:
    - name: Copy docker entrypoint script.
      template:
        src: docker-entrypoint.sh.j2
        dest: /docker-entrypoint.sh
        mode: 0755  
